main: com.serverworld.phoenix.paper.PaperPhoenix
name: ${project.name}
version: ${project.version}
author: mc-serverworld
website: mc-serverworld.com
softdepend: [PlaceholderAPI,worldMISF-worlduserdata]

commands:
  misf:
    description: Basic misf command.
    aliases: [misf]
  back:
    description: Teleport you to your last location.
    usage: /back
  home:
    description: Teleport you back to your home.
    usage: /home
  sethome:
    description: Set current location as your home.
    usage: /sethome
  spawn:
    description: Teleport you to spawn.
    usage: /spawn
  tpa:
    description: Sent a teleport request to the specific player.
    usage: /tpa [player]
  tpaccept:
    description: Accept the teleport request.
    usage: /tpaccept
  tpahere:
    description: Sent a teleport request to the specific player to you.
    usage: /tpahere [player]
  tpdeny:
    description: Deny the teleport request.
    usage: /tpdeny

permissions:
  misf.command.back:
    default: false
  misf.command.help:
    default: false
  misf.command.home:
    default: false
  misf.command.info:
    default: false
  misf.command.set.time:
    default: false
  misf.command.set.weather:
    default: false
  misf.command.sethome:
    default: false
  misf.command.login:
    default: false
  misf.command.test:
    default: false
  misf.command.tpa:
    default: false
  misf.command.tpaccept:
    default: false
  misf.command.tpahere:
    default: false
  misf.command.tpdeny:
    default: false
  misf.command.tpserver:
    default: false
  misf.command.warpsv:
    default: false
  misf.notify:
    default: false
  misf.debug:
    default: false

  misf.*:
    children:
      misf.command.back: true
      midf.command.help: true
      misf.command.info: true
      misf.command.set.time: true
      misf.command.set.weather: true
      misf.command.login: true
      misf.command.test: true
      misf.command.tpa: true
      misf.command.tpaccept: true
      misf.command.tpahere: true
      misf.command.tpdeny: true
      misf.command.tpserver: true
      misf.command.warpsv: true
    misf.command.*:
      children:
        misf.command.back: true
        midf.command.help: true
        misf.command.info: true
        misf.command.set.time: true
        misf.command.set.weather: true
        misf.command.login: true
        misf.command.test: true
        misf.command.tpa: true
        misf.command.tpaccept: true
        misf.command.tpahere: true
        misf.command.tpdeny: true
        misf.command.tpserver: true
        misf.command.warpsv: true
    misf.player:
      children:
        misf.command.back: true
        misf.command.help: true
        misf.command.home: true
        misf.command.login: true
        misf.command.sethome: true
        misf.command.tpa: true
        misf.command.tpaccept: true
        misf.command.tpahere: true
        misf.command.tpdeny: true
        misf.command.warpsv: true
