main: com.serverworld.phoenix.paper.PaperPhoenix
name: ${project.name}
version: ${project.version}
author: mc-serverworld
website: mc-serverworld.com
softdepend: [PlaceholderAPI,worldMISF-worlduserdata]

commands:
  misf:
    description: Basic misf command.
    aliases: [misf]
  back:
    description: Teleports you to your last location.
    usage: /back

permissions:
  misf.command.back:
    default: false
  misf.command.help:
    default: false
  misf.command.info:
    default: false
  misf.command.set.time:
    default: false
  misf.command.set.weather:
    default: false
  misf.command.login:
    default: false
  misf.command.test:
    default: false
  misf.command.tpa:
    default: false
  misf.command.tpahere:
    default: false
  misf.command.tpserver:
    default: false
  misf.command.warpsv:
    default: false
  misf.notify:
    default: false

  misf.*:
    children:
      misf.command.back: true
      midf.command.help: true
      misf.command.info: true
      misf.command.set.time: true
      misf.command.set.weather: true
      misf.command.login: true
      misf.command.test: true
      misf.command.tpa: true
      misf.command.tpahere: true
      misf.command.tpserver: true
      misfp.command.warpsv: true
    misf.command.*:
      children:
        misf.command.back: true
        midf.command.help: true
        misf.command.info: true
        misf.command.set.time: true
        misf.command.set.weather: true
        misf.command.login: true
        misf.command.test: true
        misf.command.tpa: true
        misf.command.tpahere: true
        misf.command.tpserver: true
        misfp.command.warpsv: true
    misf.player:
      children:
        misf.command.back: true
        misf.command.help: true
        misf.command.login: true
        misf.command.tpa: true
        misf.command.tpahere: true
        misf.command.warpsv: true
