main: com.serverworld.SpigotworldUserProfile.spigot.SpigotworldUserProfile
name: ${project.name}
version: ${project.version}
authors:
  - paul0665
  - mc-serverworld
website: mc-serverworld.com
softdepend: [PlaceholderAPI]
