# ${project.name}
# Version: ${project.version}
# Gitgub: https://github.com/mc-serverworld/worldMISF
configinfo:
  api-version: 2
  debug: false

worldinfo:
  chunksize: 5000
  worldsize: 35000
