main: com.serverworld.phoenix.bungee.BungeePhoenixConfig
name: ${project.name}
version: ${project.version}
author: mc-serverworld
website: www.mc-serverworld.com

commands:
  midfbungeecord:
    description: Basic misf command.
    aliases: [misfbungee]
permissions:
      misfbungeecord.command.help:
        default: false
      misfbungeecord.command.info:
        default: false
      misfbungeecord.command.sudo.setup:
        default: false
      misfbungeecord.notify:
        default: false