main: com.serverworld.phoenix.bungee.BungeePhoenix
name: ${project.name}
version: ${project.version}
author: mc-serverworld
website: www.mc-serverworld.com
depends: [worldMISF-worlduserdata,worldSocket]

commands:
  midfbungeecord:
    description: Basic misf command.
    aliases: [misfbungee]
  tpa:
    description: Sent a teleport request to the specific player.
    usage: /tpa [player]
  tpahere:
    description: Sent a teleport request to the specific player to you.
    usage: /tpahere [player]

permissions:
  misfbungeecord.command.help:
    default: false
  misfbungeecord.command.info:
    default: false
  misfbungeecord.command.sudo.setup:
    default: false
  misfbungeecord.notify:
    default: false
  misf.command.tpa:
    default: true
  misf.command.tpahere:
    default: true